sonata_admin:
    title: 'Diego Admin'
    search: false
    show_mosaic_button: false
    default_admin_services:
        label_translator_strategy: 'App\Admin\Service\LabelTranslatorStrategy'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            default:
                keep_open: true
                label: Obsah
                items:
                    - App\Admin\PostAdmin
                    - App\Admin\CommentAdmin
                    - route: app_logout
                      label: Odhlásit
    assets:
        extra_stylesheets:
            - styles/admin.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
