sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            default:
                keep_open: true
                label: Obsah
                items:
                    - App\Admin\PostAdmin
                    - App\Admin\CommentAdmin

    assets:
        extra_stylesheets:
            - styles/admin.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
